import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const { imageUrl } = await req.json();
    if (!imageUrl) {
      return new Response(JSON.stringify({ error: "imageUrl is required" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) throw new Error("LOVABLE_API_KEY is not configured");

    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash",
        messages: [
          {
            role: "system",
            content: `You are an AI content detection and content safety expert. Your job is to analyze images and determine:
1. Whether they were generated by AI or are real photographs/traditional art.
2. Whether the content is family-friendly (safe for all ages).

AI-generation indicators:
- Unnatural skin textures, overly smooth or plastic-looking faces
- Inconsistent lighting or shadows
- Warped or extra fingers, hands, teeth
- Text that is garbled or nonsensical
- Repeating patterns or textures that look procedurally generated
- Overly perfect symmetry
- Uncanny valley effects on people
- Blending artifacts around edges of objects
- Inconsistent perspective or depth
- Stylistic hallmarks of known AI tools (Midjourney aesthetic, DALL-E style, Stable Diffusion artifacts)

Non-family-friendly indicators:
- Nudity or sexual content
- Graphic violence or gore
- Drug use or drug paraphernalia
- Hateful or extremist imagery
- Disturbing or horror content inappropriate for children

Respond ONLY with JSON.`,
          },
          {
            role: "user",
            content: [
              {
                type: "text",
                text: "Analyze this image. Is it AI-generated? Is it family-friendly? Respond with the tool call.",
              },
              {
                type: "image_url",
                image_url: { url: imageUrl },
              },
            ],
          },
        ],
        tools: [
          {
            type: "function",
            function: {
              name: "ai_detection_result",
              description: "Return the AI detection analysis result",
              parameters: {
                type: "object",
                properties: {
                  is_ai_generated: { type: "boolean", description: "Whether the image appears to be AI-generated" },
                  confidence: { type: "number", description: "Confidence score from 0.0 to 1.0" },
                  reason: { type: "string", description: "Brief explanation of the determination" },
                  is_family_friendly: { type: "boolean", description: "Whether the content is safe for all ages" },
                },
                required: ["is_ai_generated", "confidence", "reason", "is_family_friendly"],
                additionalProperties: false,
              },
            },
          },
        ],
        tool_choice: { type: "function", function: { name: "ai_detection_result" } },
      }),
    });

    if (!response.ok) {
      if (response.status === 429) {
        return new Response(JSON.stringify({ error: "Rate limit exceeded, please try again later." }), {
          status: 429,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      if (response.status === 402) {
        return new Response(JSON.stringify({ error: "AI credits exhausted. Please add funds." }), {
          status: 402,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      const t = await response.text();
      console.error("AI gateway error:", response.status, t);
      throw new Error("AI analysis failed");
    }

    const data = await response.json();

    // Extract tool call result
    const toolCall = data.choices?.[0]?.message?.tool_calls?.[0];
    if (toolCall?.function?.arguments) {
      const result = JSON.parse(toolCall.function.arguments);
      return new Response(JSON.stringify(result), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Fallback: try parsing from content
    const content = data.choices?.[0]?.message?.content || "";
    const jsonMatch = content.match(/\{[\s\S]*\}/);
    if (jsonMatch) {
      const result = JSON.parse(jsonMatch[0]);
      return new Response(JSON.stringify(result), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Default: allow but unverified
    return new Response(
      JSON.stringify({ is_ai_generated: false, confidence: 0, reason: "Could not determine" }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (e) {
    console.error("ai-filter error:", e);
    return new Response(
      JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
